In [47]:
import pandas as pd

In [48]:
dataset = pd.read_csv("datasets/Training.csv")

In [49]:
dataset.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [50]:
dataset.shape

(4920, 133)

In [51]:
dataset['prognosis'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [52]:
len(dataset['prognosis'].unique())

41

In [53]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [54]:
X = dataset.drop("prognosis" , axis=1)
Y = dataset['prognosis']

In [55]:
X

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
0     ...                   0           0         0             0   
1     ...                   0           0         0             0   
2     ...                   0           0         0             0   
3     ...                   0           0         0             0   
4     ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
4915  ...                   0           0         0             0   
4916  ...                   1           1         1             0   
4917  ...                   0           0         0             0   
4918  ...                   0           0         0             1   
4919  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                       0                     0                   0        0   
1                       0                     0                   0        0   
2                       0                     0                   0        0   
3                       0                     0                   0        0   
4                       0                     0                   0        0   
...                   ...                   ...                 ...      ...   
4915                    0                     0                   0        0   
4916                    0                     0                   0        0   
4917                    0                     0                   0        0   
4918                    1                     1                   1        0   
4919                    0                     0                   0        1   

      red_sore_around_nose  yellow_crust_ooze  
0                        0                  0  
1                        0                  0  
2                        0                  0  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
4915                     0                  0  
4916              

In [56]:
Y

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...                   
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object

In [57]:
le = LabelEncoder()
le.fit(Y)
y = le.transform(Y)

In [58]:
y

array([15, 15, 15, ..., 38, 35, 27])

In [59]:
 X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.3,random_state=20)

In [60]:
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((3444, 132), (1476, 132), (3444,), (1476,))

In [61]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

# create a dictionary to store models
models = {
    "SVC":SVC(kernel='linear'),
    "RandomForest": RandomForestClassifier(n_estimators=100,random_state=42),
    "GrandientBoosting":GradientBoostingClassifier(n_estimators=100,random_state=42),
    "KNeighbors":KNeighborsClassifier(n_neighbors=5),
    "MultinomialNB":MultinomialNB()
}
for model_name, model in models.items():

    # train model
    model.fit(X_train,Y_train)

    # test model
    predictions = model.predict(X_test)

    # calculate accuracy
    accuracy = accuracy_score(Y_test,predictions)

    # calculate confusion matrix
    cm = confusion_matrix(Y_test,predictions)

    print(f"{model_name} accuracy : {accuracy}")
    print(f"{model_name} Confusion Matrix: ")
    print(np.array2string(cm,separator=', '))

SVC accuracy : 1.0
SVC Confusion Matrix: 
[[40,  0,  0, ...,  0,  0,  0],
 [ 0, 43,  0, ...,  0,  0,  0],
 [ 0,  0, 28, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 34,  0,  0],
 [ 0,  0,  0, ...,  0, 41,  0],
 [ 0,  0,  0, ...,  0,  0, 31]]
RandomForest accuracy : 1.0
RandomForest Confusion Matrix: 
[[40,  0,  0, ...,  0,  0,  0],
 [ 0, 43,  0, ...,  0,  0,  0],
 [ 0,  0, 28, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 34,  0,  0],
 [ 0,  0,  0, ...,  0, 41,  0],
 [ 0,  0,  0, ...,  0,  0, 31]]
GrandientBoosting accuracy : 1.0
GrandientBoosting Confusion Matrix: 
[[40,  0,  0, ...,  0,  0,  0],
 [ 0, 43,  0, ...,  0,  0,  0],
 [ 0,  0, 28, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 34,  0,  0],
 [ 0,  0,  0, ...,  0, 41,  0],
 [ 0,  0,  0, ...,  0,  0, 31]]
KNeighbors accuracy : 1.0
KNeighbors Confusion Matrix: 
[[40,  0,  0, ...,  0,  0,  0],
 [ 0, 43,  0, ...,  0,  0,  0],
 [ 0,  0, 28, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 34,  0,  0],
 [ 0,  0,  0, ...,  0, 41,  0],
 [ 0,  0,  0

In [62]:
svc = SVC(kernel='linear')
svc.fit(X_train,Y_train)
ypred = svc.predict(X_test)
accuracy_score(Y_test,ypred)

1.0

In [63]:
# saving model
# import pickle
# pickle.dump(svc,open("models/svc.pkl",'wb'))

In [64]:
# Load model
svc = pickle.load(open("models/svc.pkl",'rb'))

<class 'NameError'>: name 'pickle' is not defined

In [65]:
X_test

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
4037        0          0                     0                    0   
4191        0          0                     0                    0   
432         0          0                     0                    0   
1266        1          0                     0                    0   
3765        0          0                     0                    0   
...       ...        ...                   ...                  ...   
2837        0          0                     0                    0   
2327        0          0                     0                    0   
1399        1          1                     0                    0   
1906        0          0                     0                    1   
4474        0          0                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
4037          0       0           1             0        0                 0   
4191          0       0           0             0        0                 0   
432           0       0           0             1        1                 0   
1266          0       0           0             0        0                 0   
3765          0       0           1             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
2837          0       0           0             0        0                 0   
2327          0       1           0             0        0                 0   
1399          0       0           0             0        0                 0   
1906          0       1           0             0        0                 0   
4474          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
4037  ...                   0           0         0             0   
4191  ...                   0           0         0             0   
432   ...                   0           0         0             0   
1266  ...                   0           0         0             0   
3765  ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
2837  ...                   0           0         0             0   
2327  ...                   0           0         0             0   
1399  ...                   0           0         0             0   
1906  ...                   0           0         0             0   
4474  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
4037                    0                     0                   0        0   
4191                    0                     0                   0        0   
432                     0                     0                   0        0   
1266                    0                     0                   0        0   
3765                    0                     0                   0        0   
...                   ...                   ...                 ...      ...   
2837                    0                     0                   0        0   
2327                    0                     0                   0        0   
1399                    0                     0                   0        0   
1906                    0                     0                   0        0   
4474                    0                     0                   0        0   

      red_sore_around_nose  yellow_crust_ooze  
4037                     0                  0  
4191                     0                  0  
432                      0                  0  
1266                     0                  0  
3765                     0                  0  
...                    ...                ...  
2837                     0                  0  
2327              

In [66]:
X_test.iloc[0]

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
small_dents_in_nails    0
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
Name: 4037, Length: 132, dtype: int64

In [67]:
X_test.iloc[0].values

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [68]:
X_test.iloc[0].values.reshape(1,-1)

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [69]:
svc.predict(X_test.iloc[0].values.reshape(1,-1))

/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([40])

In [70]:
Y_test

array([40,  6, 16, ...,  8, 10, 33])

In [71]:
Y_test[0]

40

In [72]:
# test 1
print("Predicted Label :", svc.predict(X_test.iloc[0].values.reshape(1,-1)))
print("Actual Label :", Y_test[0])

/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


Predicted Label : [40]
Actual Label : 40


In [73]:
# test 2
print("Predicted Label :", svc.predict(X_test.iloc[10].values.reshape(1,-1)))
print("Actual Label :", Y_test[10])

/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


Predicted Label : [20]
Actual Label : 20


In [74]:
 sys_des = pd.read_csv('datasets/symtoms_df.csv')
precautions = pd.read_csv('datasets/precautions_df.csv')
workout = pd.read_csv('datasets/workout_df.csv')
description = pd.read_csv('datasets/description.csv')
medications = pd.read_csv('datasets/medications.csv')
diets = pd.read_csv('datasets/diets.csv')

In [75]:
diets

Disease  \
0                         Fungal infection   
1                                  Allergy   
2                                     GERD   
3                      Chronic cholestasis   
4                            Drug Reaction   
5                     Peptic ulcer disease   
6                                     AIDS   
7                                 Diabetes   
8                          Gastroenteritis   
9                         Bronchial Asthma   
10                            Hypertension   
11                                Migraine   
12                    Cervical spondylosis   
13            Paralysis (brain hemorrhage)   
14                                Jaundice   
15                                 Malaria   
16                             Chicken pox   
17                                  Dengue   
18                                 Typhoid   
19                             hepatitis A   
20                             Hepatitis B   
21                             Hepatitis C   
22                             Hepatitis D   
23                             Hepatitis E   
24                     Alcoholic hepatitis   
25                            Tuberculosis   
26                             Common Cold   
27                               Pneumonia   
28            Dimorphic hemmorhoids(piles)   
29                            Heart attack   
30                          Varicose veins   
31                          Hypothyroidism   
32                         Hyperthyroidism   
33                            Hypoglycemia   
34                         Osteoarthristis   
35                               Arthritis   
36  (vertigo) Paroymsal Positional Vertigo   
37                                    Acne   
38                 Urinary tract infection   
39                               Psoriasis   
40                                Impetigo   

                                                 Diet  
0   ['Antifungal Diet', 'Probiotics', 'Garlic', 'C...  
1   ['Elimination Diet', 'Omega-3-rich foods', 'Vi...  
2   ['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'...  
3   ['Low-Fat Diet', 'High-Fiber Diet', 'Lean prot...  
4   ['Antihistamine Diet', 'Omega-3-rich foods', '...  
5   ['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'...  
6   ['Balanced Diet', 'Protein-rich foods', 'Fruit...  
7   ['Low-Glycemic Diet', 'Fiber-rich foods', 'Lea...  
8   ['Bland Diet', 'Bananas', 'Rice', 'Applesauce'...  
9   ['Anti-Inflammatory Diet', 'Omega-3-rich foods...  
10  ['DASH Diet', 'Low-sodium foods', 'Fruits and ...  
11  ['Migraine Diet', 'Low-Tyramine Diet', 'Caffei...  
12  ['Arthritis Diet', 'Anti-Inflammatory Diet', '...  
13  ['Heart-Healthy Diet', 'Low-sodium foods', 'Fr...  
14  ['Liver-Healthy Diet', 'Low-fat Diet', 'Fruits...  
15  ['Malaria Diet', 'Hydration', 'High-Calorie Di...  
16  ['Chicken Pox Diet', 'High-Calorie Diet', 'Sof...  
17  ['Dengue Diet', 'Hydration', 'High-Calorie Die...  
18  ['Typhoid Diet', 'High-Calorie Diet', 'Soft an...  
19  ['Hepatitis A Diet', 'High-Calorie Diet', 'Sof...  
20  ['Hepatitis B Diet', 'High-Calorie Diet', 'Sof...  
21  ['Hepatitis C Diet', 'High-Calorie Diet', 'Sof...  
22  ['Hepatitis D Diet', 'High-Calorie Diet', 'Sof...  
23  ['Hepatitis E Diet', 'High-Calorie Diet', 'Sof...  
24  ['Liver-Healthy Diet', 'Low-fat Diet', 'Fruits...  
25  ['TB Diet', 'High-Calorie Diet', 'Soft and bla...  
26  ['Cold Diet', 'Hydration', 'Warm fluids', 'Res...  
27  ['Pneumonia Diet', 'High-Calorie Diet', 'Soft ...  
28  ['Hemorrhoids Diet', 'High-Fiber Diet', 'Hydra...  
29  ['Heart-Healthy Diet', 'Low-sodium foods', 'Fr...  
30  ['Varicose Veins Diet', 'High-Fiber Diet', 'Fr...  
31  ['Hypothyroidism Diet', 'Iodine-rich foods', '...  
32  ['Hyperthyroidism Diet', 'Low-Iodine Diet', 'C...  
33  ['Hypoglycemia Diet', 'Complex carbohydrates',...  
34  ['Arthritis Diet', 'Anti-Inflammatory Diet', '...  
35  ['Arthritis Diet', 'Anti-Inflammatory Diet', '...  
36  ['Vertigo Diet', 'Low-Salt

In [76]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [91]:
import numpy as np  # Import numpy library

#============================================================
# custome and helping functions
#==========================helper funtions================
def helper(dis):
    desc = description[description['Disease'] == dis]['Description']
    desc = " ".join([w for w in desc])

    pre = precautions[precautions['Disease'] == dis][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
    pre = [col for col in pre.values]

    med = medications[medications['Disease'] == dis]['Medication']
    med = [med for med in med.values]

    die = diets[diets['Disease'] == dis]['Diet']
    die = [die for die in die.values]

    wrkout = workout[workout['disease'] == dis] ['workout']
    return desc,pre,med,die,wrkout

symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of_urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic_patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer disease', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemorrhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthritis', 5: 'Arthritis', 0: '(vertigo) Paroxysmal Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}

# model prediction function
def get_predicted_value(patient_symptoms):
    input_vector = np.zeros(len(symptoms_dict))

    for item in patient_symptoms:
        input_vector[symptoms_dict[item]] = 1
    return diseases_list[svc.predict([input_vector])[0]]




In [100]:
# test 1
symptoms =  await input("Enter your symptoms -> ")
user_symptoms = [s.strip() for s in symptoms.split(',')]

user_symptoms = [sym.strip("[]' ") for sym in user_symptoms] 

predicted_disease = get_predicted_value(user_symptoms)

desc,pre,med,die,wrkout = helper(predicted_disease)





Enter your symptoms ->  itching , skin_rash , shivering


In [103]:
# results print
print("=================predicted disease============")
print(predicted_disease)
print("=================description==================")
print(desc)
print("=================precautions==================")
i = 1
for p_i in pre[0]:
    print(i, ": ", p_i)
    i += 1

print("=================medications==================")
i = 1
for m_i in med:
    print(i, ": ", m_i)
    i += 1

print("=================workout==================")
i = 1
for w_i in wrkout:
    print(i, ": ", w_i)
    i += 1

print("=================diets==================")
i = 1
for d_i in die:
    print(i, ": ", d_i)
    i += 1

=================predicted disease============
Fungal infection
=================description==================
Fungal infection is a common skin condition caused by fungi.
=================precautions==================
1 :  bath twice
2 :  use detol or neem in bathing water
3 :  keep infected area dry
4 :  use clean cloths
=================medications==================
1 :  ['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']
=================workout==================
1 :  Avoid sugary foods
2 :  Consume probiotics
3 :  Increase intake of garlic
4 :  Include yogurt in diet
5 :  Limit processed foods
6 :  Stay hydrated
7 :  Consume green tea
8 :  Eat foods rich in zinc
9 :  Include turmeric in diet
10 :  Eat fruits and vegetables
=================diets==================
1 :  ['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']


In [104]:
import sklearn
print(sklearn.__version__)

1.4.2
